apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mymonthlyblogarticlebot.fullname" . }}
  labels:
    {{- include "mymonthlyblogarticlebot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mymonthlyblogarticlebot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mymonthlyblogarticlebot.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: MICROSOFT_APP_ID
            value: {{ .Values.image.env.microsoftAppId }}
          - name: MICROSOFT_APP_PASSWORD
            value: {{ .Values.image.env.microsoftAppPassword }}
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            value: {{ .Values.image.env.appInsights.instrumentationKey }}
          - name: AZURE_SEARCH_SERVICE_NAME
            value: {{ .Values.image.env.search.serviceName }}
          - name: AZURE_SEARCH_INDEX_NAME
            value: {{ .Values.image.env.search.indexName }}
          - name: AZURE_SEARCH_SERVICE_QUERY_API_KEY
            value: {{ .Values.image.env.search.serviceQueryApiKey }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
