apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mymonthlyblogarticlebot.fullname" . }}
  labels:
    {{- include "mymonthlyblogarticlebot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mymonthlyblogarticlebot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mymonthlyblogarticlebot.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          env:
          - name: MicrosoftAppId
            valueFrom:
              secretKeyRef:
                name: {{ include "mymonthlyblogarticlebot.fullname" . }}
                key: microsoftAppId
          - name: MicrosoftAppPassword
            valueFrom:
              secretKeyRef:
                name: {{ include "mymonthlyblogarticlebot.fullname" . }}
                key: microsoftAppPassword
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            valueFrom:
              secretKeyRef:
                name: {{ include "mymonthlyblogarticlebot.fullname" . }}
                key: appInsightsInstrumentationKey
          - name: AZURE_SEARCH_SERVICE_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "mymonthlyblogarticlebot.fullname" . }}
                key: searchServiceName
          - name: AZURE_SEARCH_INDEX_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "mymonthlyblogarticlebot.fullname" . }}
                key: searchIndexName
          - name: AZURE_SEARCH_SERVICE_QUERY_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "mymonthlyblogarticlebot.fullname" . }}
                key: searchServiceQueryApiKey
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
