{{- if .Values.networkpolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: denyall-netpol
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bot-netpol
spec:
  podSelector:
    matchLabels:
      app: {{ include "mymonthlyblogarticlebot.name" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-ingress
    ports:
     - port: {{ .Values.image.port }}
       protocol: TCP
  egress:
  - to: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-ingress-netpol
spec:
  podSelector:
    matchLabels:
      app: nginx-ingress
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from: []
    ports:
     - port: 443
       protocol: TCP
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "mymonthlyblogarticlebot.name" . }}
    ports:
     - port: {{ .Values.image.port }}
       protocol: TCP
{{- end }}