apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mymonthlyblogarticlebot.fullname" . }}
  labels:
    {{- include "mymonthlyblogarticlebot.labels" . | nindent 4 }}
type: Opaque
data:
  microsoftAppId: {{ .Values.image.env.microsoftAppId | b64enc | quote }}
  microsoftAppPassword: {{ .Values.image.env.microsoftAppPassword | b64enc | quote }}
  appInsightsInstrumentationKey: {{ .Values.image.env.appInsights.instrumentationKey | b64enc | quote }}
  searchServiceName: {{ .Values.image.env.search.serviceName | b64enc | quote }}
  searchIndexName: {{ .Values.image.env.search.indexName | b64enc | quote }}
  searchServiceQueryApiKey: {{ .Values.image.env.search.serviceQueryApiKey | b64enc | quote }}