trigger:
  batch: true
  branches:
    include: 
    - '*'

pr: none

variables:
  vmImage: 'ubuntu-16.04'
  projectFolder: 'MyMonthlyBlogArticle.Bot'
  registryServerName: '$(registryName).azurecr.io'
  imageName: mymonthyblogarticlebot
  imageTag: $(build.buildId)
  # define 3 more variables: registryName, registryLogin and registryPassword in the Azure pipeline UI definition

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
  - job: 'Build'
    displayName: 'Build'
    pool:
      vmImage: $(vmImage)
    steps:
    - bash: |
        cd $(projectFolder)
        docker build \
            -t $(registryServerName)/$(imageName):$(imageTag) \
            .
      failOnStderr: true
      displayName: 'docker build'
    - bash: |
        echo $(registryPassword) | docker login \
            $(registryServerName) \
            -u $(registryLogin) \
            --password-stdin
      displayName: 'docker login'
    - bash: |
        docker push $(registryServerName)/$(imageName):$(imageTag)
      failOnStderr: true
      displayName: 'docker push'