trigger:
  batch: true
  branches:
    include: 
    - '*'

pr: none

pool:
  vmImage: 'ubuntu-16.04'

variables:
  projectFolder: 'MyMonthlyBlogArticle.Bot'
  registryServerName: '$(registryName).azurecr.io'
  imageName: mymonthyblogarticlebot
  imageTag: $(build.buildId)
  # define 3 more variables: registryName, registryLogin and registryPassword in the Azure pipeline UI definition

steps:
- bash: |
    cd $(projectFolder)
    docker build \
        -t $(registryServerName)/$(imageName):$(imageTag) \
        .
  failOnStderr: true
  displayName: 'docker build'
- bash: |
    echo $(registryPassword) | docker login \
        $(registryServerName) \
        -u $(registryLogin) \
        --password-stdin
  displayName: 'docker login'
- bash: |
    docker push $(registryServerName)/$(imageName):$(imageTag)
  failOnStderr: true
  displayName: 'docker push'